http://localhost:8887/pokemons

###
http://localhost:8887/pokemon_id/3

###
http://localhost:8887/pokemon_name/graveler

###
http://localhost:8887/abilities

###
http://localhost:8887/ability_id/5

###
http://localhost:8887/ability_name/sturdy

###
http://localhost:8887/types

###
http://localhost:8887/type/pokemon/fairy

###
http://localhost:8887/type/poison

