// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        v3.19.1
// source: proto/type/type.proto

package _type

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TypeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeId           string   `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	TypeName         string   `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	NoDamageTo       []string `protobuf:"bytes,3,rep,name=no_damage_to,json=noDamageTo,proto3" json:"no_damage_to,omitempty"`
	HalfDamageTo     []string `protobuf:"bytes,4,rep,name=half_damage_to,json=halfDamageTo,proto3" json:"half_damage_to,omitempty"`
	DoubleDamageTo   []string `protobuf:"bytes,5,rep,name=double_damage_to,json=doubleDamageTo,proto3" json:"double_damage_to,omitempty"`
	NoDamageFrom     []string `protobuf:"bytes,6,rep,name=no_damage_from,json=noDamageFrom,proto3" json:"no_damage_from,omitempty"`
	HalfDamageFrom   []string `protobuf:"bytes,7,rep,name=half_damage_from,json=halfDamageFrom,proto3" json:"half_damage_from,omitempty"`
	DoubleDamageFrom []string `protobuf:"bytes,8,rep,name=double_damage_from,json=doubleDamageFrom,proto3" json:"double_damage_from,omitempty"`
}

func (x *TypeInfo) Reset() {
	*x = TypeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeInfo) ProtoMessage() {}

func (x *TypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeInfo.ProtoReflect.Descriptor instead.
func (*TypeInfo) Descriptor() ([]byte, []int) {
	return file_proto_type_type_proto_rawDescGZIP(), []int{0}
}

func (x *TypeInfo) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *TypeInfo) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *TypeInfo) GetNoDamageTo() []string {
	if x != nil {
		return x.NoDamageTo
	}
	return nil
}

func (x *TypeInfo) GetHalfDamageTo() []string {
	if x != nil {
		return x.HalfDamageTo
	}
	return nil
}

func (x *TypeInfo) GetDoubleDamageTo() []string {
	if x != nil {
		return x.DoubleDamageTo
	}
	return nil
}

func (x *TypeInfo) GetNoDamageFrom() []string {
	if x != nil {
		return x.NoDamageFrom
	}
	return nil
}

func (x *TypeInfo) GetHalfDamageFrom() []string {
	if x != nil {
		return x.HalfDamageFrom
	}
	return nil
}

func (x *TypeInfo) GetDoubleDamageFrom() []string {
	if x != nil {
		return x.DoubleDamageFrom
	}
	return nil
}

type PokemonsOfType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeId      string   `protobuf:"bytes,1,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	TypeName    string   `protobuf:"bytes,2,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	PokemonName []string `protobuf:"bytes,3,rep,name=pokemon_name,json=pokemonName,proto3" json:"pokemon_name,omitempty"`
}

func (x *PokemonsOfType) Reset() {
	*x = PokemonsOfType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_type_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PokemonsOfType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonsOfType) ProtoMessage() {}

func (x *PokemonsOfType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_type_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonsOfType.ProtoReflect.Descriptor instead.
func (*PokemonsOfType) Descriptor() ([]byte, []int) {
	return file_proto_type_type_proto_rawDescGZIP(), []int{1}
}

func (x *PokemonsOfType) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *PokemonsOfType) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *PokemonsOfType) GetPokemonName() []string {
	if x != nil {
		return x.PokemonName
	}
	return nil
}

type ListTypesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListTypesRequest) Reset() {
	*x = ListTypesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_type_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTypesRequest) ProtoMessage() {}

func (x *ListTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_type_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTypesRequest.ProtoReflect.Descriptor instead.
func (*ListTypesRequest) Descriptor() ([]byte, []int) {
	return file_proto_type_type_proto_rawDescGZIP(), []int{2}
}

type ListTypesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeInfos []*TypeInfo `protobuf:"bytes,1,rep,name=type_infos,json=typeInfos,proto3" json:"type_infos,omitempty"`
}

func (x *ListTypesResponse) Reset() {
	*x = ListTypesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_type_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTypesResponse) ProtoMessage() {}

func (x *ListTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_type_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTypesResponse.ProtoReflect.Descriptor instead.
func (*ListTypesResponse) Descriptor() ([]byte, []int) {
	return file_proto_type_type_proto_rawDescGZIP(), []int{3}
}

func (x *ListTypesResponse) GetTypeInfos() []*TypeInfo {
	if x != nil {
		return x.TypeInfos
	}
	return nil
}

type GetPokemonsOfTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeName string `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
}

func (x *GetPokemonsOfTypeRequest) Reset() {
	*x = GetPokemonsOfTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_type_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPokemonsOfTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPokemonsOfTypeRequest) ProtoMessage() {}

func (x *GetPokemonsOfTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_type_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPokemonsOfTypeRequest.ProtoReflect.Descriptor instead.
func (*GetPokemonsOfTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_type_type_proto_rawDescGZIP(), []int{4}
}

func (x *GetPokemonsOfTypeRequest) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

type GetPokemonsOfTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PokemonsOfType *PokemonsOfType `protobuf:"bytes,1,opt,name=pokemons_of_type,json=pokemonsOfType,proto3" json:"pokemons_of_type,omitempty"`
}

func (x *GetPokemonsOfTypeResponse) Reset() {
	*x = GetPokemonsOfTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_type_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPokemonsOfTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPokemonsOfTypeResponse) ProtoMessage() {}

func (x *GetPokemonsOfTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_type_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPokemonsOfTypeResponse.ProtoReflect.Descriptor instead.
func (*GetPokemonsOfTypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_type_type_proto_rawDescGZIP(), []int{5}
}

func (x *GetPokemonsOfTypeResponse) GetPokemonsOfType() *PokemonsOfType {
	if x != nil {
		return x.PokemonsOfType
	}
	return nil
}

type GetTypeInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeName string `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
}

func (x *GetTypeInfoRequest) Reset() {
	*x = GetTypeInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_type_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTypeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTypeInfoRequest) ProtoMessage() {}

func (x *GetTypeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_type_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTypeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetTypeInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_type_type_proto_rawDescGZIP(), []int{6}
}

func (x *GetTypeInfoRequest) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

type GetTypeInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeInfo *TypeInfo `protobuf:"bytes,1,opt,name=type_info,json=typeInfo,proto3" json:"type_info,omitempty"`
}

func (x *GetTypeInfoResponse) Reset() {
	*x = GetTypeInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_type_type_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTypeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTypeInfoResponse) ProtoMessage() {}

func (x *GetTypeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_type_type_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTypeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetTypeInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_type_type_proto_rawDescGZIP(), []int{7}
}

func (x *GetTypeInfoResponse) GetTypeInfo() *TypeInfo {
	if x != nil {
		return x.TypeInfo
	}
	return nil
}

var File_proto_type_type_proto protoreflect.FileDescriptor

var file_proto_type_type_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x79, 0x70, 0x65, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb0, 0x02, 0x0a, 0x08,
	0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x79, 0x70, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x79, 0x70, 0x65, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0c, 0x6e, 0x6f, 0x5f, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x6f, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x6f,
	0x12, 0x24, 0x0a, 0x0e, 0x68, 0x61, 0x6c, 0x66, 0x5f, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x5f,
	0x74, 0x6f, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x68, 0x61, 0x6c, 0x66, 0x44, 0x61,
	0x6d, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x12, 0x28, 0x0a, 0x10, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65,
	0x5f, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0e, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x6f,
	0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x6f, 0x5f, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x44, 0x61, 0x6d, 0x61,
	0x67, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x28, 0x0a, 0x10, 0x68, 0x61, 0x6c, 0x66, 0x5f, 0x64,
	0x61, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0e, 0x68, 0x61, 0x6c, 0x66, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x46, 0x72, 0x6f, 0x6d,
	0x12, 0x2c, 0x0a, 0x12, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x5f, 0x64, 0x61, 0x6d, 0x61, 0x67,
	0x65, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x64, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x22, 0x69,
	0x0a, 0x0e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x73, 0x4f, 0x66, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x79, 0x70,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x79,
	0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x42, 0x0a,
	0x11, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2d, 0x0a, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x74, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x73, 0x22, 0x37, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x73,
	0x4f, 0x66, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5b, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x73, 0x4f, 0x66, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x10, 0x70, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x73, 0x5f, 0x6f, 0x66, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x73, 0x4f, 0x66, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x73, 0x4f, 0x66, 0x54, 0x79, 0x70, 0x65, 0x22, 0x31, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x42, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2b, 0x0a, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x32, 0xac,
	0x02, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x4c, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x08, 0x12, 0x06, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x77, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x73, 0x4f, 0x66, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x73, 0x4f, 0x66, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x73, 0x4f, 0x66, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x1b, 0x12, 0x19, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x2f, 0x7b, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x12, 0x5d,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x2f, 0x7b, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x42, 0x0c, 0x5a,
	0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_type_type_proto_rawDescOnce sync.Once
	file_proto_type_type_proto_rawDescData = file_proto_type_type_proto_rawDesc
)

func file_proto_type_type_proto_rawDescGZIP() []byte {
	file_proto_type_type_proto_rawDescOnce.Do(func() {
		file_proto_type_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_type_type_proto_rawDescData)
	})
	return file_proto_type_type_proto_rawDescData
}

var file_proto_type_type_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_type_type_proto_goTypes = []interface{}{
	(*TypeInfo)(nil),                  // 0: type.TypeInfo
	(*PokemonsOfType)(nil),            // 1: type.PokemonsOfType
	(*ListTypesRequest)(nil),          // 2: type.ListTypesRequest
	(*ListTypesResponse)(nil),         // 3: type.ListTypesResponse
	(*GetPokemonsOfTypeRequest)(nil),  // 4: type.GetPokemonsOfTypeRequest
	(*GetPokemonsOfTypeResponse)(nil), // 5: type.GetPokemonsOfTypeResponse
	(*GetTypeInfoRequest)(nil),        // 6: type.GetTypeInfoRequest
	(*GetTypeInfoResponse)(nil),       // 7: type.GetTypeInfoResponse
}
var file_proto_type_type_proto_depIdxs = []int32{
	0, // 0: type.ListTypesResponse.type_infos:type_name -> type.TypeInfo
	1, // 1: type.GetPokemonsOfTypeResponse.pokemons_of_type:type_name -> type.PokemonsOfType
	0, // 2: type.GetTypeInfoResponse.type_info:type_name -> type.TypeInfo
	2, // 3: type.Type.ListTypes:input_type -> type.ListTypesRequest
	4, // 4: type.Type.GetPokemonsOfType:input_type -> type.GetPokemonsOfTypeRequest
	6, // 5: type.Type.GetTypeInfo:input_type -> type.GetTypeInfoRequest
	3, // 6: type.Type.ListTypes:output_type -> type.ListTypesResponse
	5, // 7: type.Type.GetPokemonsOfType:output_type -> type.GetPokemonsOfTypeResponse
	7, // 8: type.Type.GetTypeInfo:output_type -> type.GetTypeInfoResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_type_type_proto_init() }
func file_proto_type_type_proto_init() {
	if File_proto_type_type_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_type_type_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_type_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PokemonsOfType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_type_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTypesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_type_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTypesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_type_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPokemonsOfTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_type_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPokemonsOfTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_type_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTypeInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_type_type_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTypeInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_type_type_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_type_type_proto_goTypes,
		DependencyIndexes: file_proto_type_type_proto_depIdxs,
		MessageInfos:      file_proto_type_type_proto_msgTypes,
	}.Build()
	File_proto_type_type_proto = out.File
	file_proto_type_type_proto_rawDesc = nil
	file_proto_type_type_proto_goTypes = nil
	file_proto_type_type_proto_depIdxs = nil
}
