// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        v3.19.1
// source: proto/pokemon/pokemon.proto

package pokemon

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PokemonInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PokemonId   string   `protobuf:"bytes,1,opt,name=pokemon_id,json=pokemonId,proto3" json:"pokemon_id,omitempty"`
	PokemonName string   `protobuf:"bytes,2,opt,name=pokemon_name,json=pokemonName,proto3" json:"pokemon_name,omitempty"`
	Type        []string `protobuf:"bytes,3,rep,name=type,proto3" json:"type,omitempty"`
	Ability     []string `protobuf:"bytes,4,rep,name=ability,proto3" json:"ability,omitempty"`
}

func (x *PokemonInfo) Reset() {
	*x = PokemonInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_pokemon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PokemonInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonInfo) ProtoMessage() {}

func (x *PokemonInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_pokemon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonInfo.ProtoReflect.Descriptor instead.
func (*PokemonInfo) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_pokemon_proto_rawDescGZIP(), []int{0}
}

func (x *PokemonInfo) GetPokemonId() string {
	if x != nil {
		return x.PokemonId
	}
	return ""
}

func (x *PokemonInfo) GetPokemonName() string {
	if x != nil {
		return x.PokemonName
	}
	return ""
}

func (x *PokemonInfo) GetType() []string {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *PokemonInfo) GetAbility() []string {
	if x != nil {
		return x.Ability
	}
	return nil
}

type ListPokemonsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPokemonsRequest) Reset() {
	*x = ListPokemonsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_pokemon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPokemonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPokemonsRequest) ProtoMessage() {}

func (x *ListPokemonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_pokemon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPokemonsRequest.ProtoReflect.Descriptor instead.
func (*ListPokemonsRequest) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_pokemon_proto_rawDescGZIP(), []int{1}
}

type ListPokemonsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PokemonInfos []*PokemonInfo `protobuf:"bytes,1,rep,name=pokemon_infos,json=pokemonInfos,proto3" json:"pokemon_infos,omitempty"`
}

func (x *ListPokemonsResponse) Reset() {
	*x = ListPokemonsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_pokemon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPokemonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPokemonsResponse) ProtoMessage() {}

func (x *ListPokemonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_pokemon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPokemonsResponse.ProtoReflect.Descriptor instead.
func (*ListPokemonsResponse) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_pokemon_proto_rawDescGZIP(), []int{2}
}

func (x *ListPokemonsResponse) GetPokemonInfos() []*PokemonInfo {
	if x != nil {
		return x.PokemonInfos
	}
	return nil
}

type GetPokemonByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PokemonId string `protobuf:"bytes,1,opt,name=pokemon_id,json=pokemonId,proto3" json:"pokemon_id,omitempty"`
}

func (x *GetPokemonByIDRequest) Reset() {
	*x = GetPokemonByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_pokemon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPokemonByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPokemonByIDRequest) ProtoMessage() {}

func (x *GetPokemonByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_pokemon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPokemonByIDRequest.ProtoReflect.Descriptor instead.
func (*GetPokemonByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_pokemon_proto_rawDescGZIP(), []int{3}
}

func (x *GetPokemonByIDRequest) GetPokemonId() string {
	if x != nil {
		return x.PokemonId
	}
	return ""
}

type GetPokemonByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PokemonInfo *PokemonInfo `protobuf:"bytes,1,opt,name=pokemon_info,json=pokemonInfo,proto3" json:"pokemon_info,omitempty"`
}

func (x *GetPokemonByIDResponse) Reset() {
	*x = GetPokemonByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_pokemon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPokemonByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPokemonByIDResponse) ProtoMessage() {}

func (x *GetPokemonByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_pokemon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPokemonByIDResponse.ProtoReflect.Descriptor instead.
func (*GetPokemonByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_pokemon_proto_rawDescGZIP(), []int{4}
}

func (x *GetPokemonByIDResponse) GetPokemonInfo() *PokemonInfo {
	if x != nil {
		return x.PokemonInfo
	}
	return nil
}

type GetPokemonByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PokemonName string `protobuf:"bytes,1,opt,name=pokemon_name,json=pokemonName,proto3" json:"pokemon_name,omitempty"`
}

func (x *GetPokemonByNameRequest) Reset() {
	*x = GetPokemonByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_pokemon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPokemonByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPokemonByNameRequest) ProtoMessage() {}

func (x *GetPokemonByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_pokemon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPokemonByNameRequest.ProtoReflect.Descriptor instead.
func (*GetPokemonByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_pokemon_proto_rawDescGZIP(), []int{5}
}

func (x *GetPokemonByNameRequest) GetPokemonName() string {
	if x != nil {
		return x.PokemonName
	}
	return ""
}

type GetPokemonByNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PokemonInfo *PokemonInfo `protobuf:"bytes,1,opt,name=pokemon_info,json=pokemonInfo,proto3" json:"pokemon_info,omitempty"`
}

func (x *GetPokemonByNameResponse) Reset() {
	*x = GetPokemonByNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_pokemon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPokemonByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPokemonByNameResponse) ProtoMessage() {}

func (x *GetPokemonByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_pokemon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPokemonByNameResponse.ProtoReflect.Descriptor instead.
func (*GetPokemonByNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_pokemon_proto_rawDescGZIP(), []int{6}
}

func (x *GetPokemonByNameResponse) GetPokemonInfo() *PokemonInfo {
	if x != nil {
		return x.PokemonInfo
	}
	return nil
}

var File_proto_pokemon_pokemon_proto protoreflect.FileDescriptor

var file_proto_pokemon_pokemon_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2f,
	0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d, 0x0a, 0x0b, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x22, 0x15, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x51, 0x0a, 0x14, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x39, 0x0a, 0x0d, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0c, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x36, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x37, 0x0a, 0x0c, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e,
	0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x70, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x3c, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x50,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x53, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d,
	0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b,
	0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x32, 0xdd, 0x02, 0x0a, 0x07,
	0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x5e, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f,
	0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x12, 0x09, 0x2f, 0x70,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x73, 0x12, 0x73, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x12, 0x1e, 0x2e, 0x70, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x42, 0x79,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x6f, 0x6b, 0x65,
	0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x42, 0x79,
	0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1a, 0x12, 0x18, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x2f,
	0x7b, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x7d, 0x12, 0x7d, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x12, 0x1c, 0x2f,
	0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x2f, 0x7b, 0x70, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x42, 0x0f, 0x5a, 0x0d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_pokemon_pokemon_proto_rawDescOnce sync.Once
	file_proto_pokemon_pokemon_proto_rawDescData = file_proto_pokemon_pokemon_proto_rawDesc
)

func file_proto_pokemon_pokemon_proto_rawDescGZIP() []byte {
	file_proto_pokemon_pokemon_proto_rawDescOnce.Do(func() {
		file_proto_pokemon_pokemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pokemon_pokemon_proto_rawDescData)
	})
	return file_proto_pokemon_pokemon_proto_rawDescData
}

var file_proto_pokemon_pokemon_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_pokemon_pokemon_proto_goTypes = []interface{}{
	(*PokemonInfo)(nil),              // 0: pokemon.PokemonInfo
	(*ListPokemonsRequest)(nil),      // 1: pokemon.ListPokemonsRequest
	(*ListPokemonsResponse)(nil),     // 2: pokemon.ListPokemonsResponse
	(*GetPokemonByIDRequest)(nil),    // 3: pokemon.GetPokemonByIDRequest
	(*GetPokemonByIDResponse)(nil),   // 4: pokemon.GetPokemonByIDResponse
	(*GetPokemonByNameRequest)(nil),  // 5: pokemon.GetPokemonByNameRequest
	(*GetPokemonByNameResponse)(nil), // 6: pokemon.GetPokemonByNameResponse
}
var file_proto_pokemon_pokemon_proto_depIdxs = []int32{
	0, // 0: pokemon.ListPokemonsResponse.pokemon_infos:type_name -> pokemon.PokemonInfo
	0, // 1: pokemon.GetPokemonByIDResponse.pokemon_info:type_name -> pokemon.PokemonInfo
	0, // 2: pokemon.GetPokemonByNameResponse.pokemon_info:type_name -> pokemon.PokemonInfo
	1, // 3: pokemon.Pokemon.ListPokemons:input_type -> pokemon.ListPokemonsRequest
	3, // 4: pokemon.Pokemon.GetPokemonByID:input_type -> pokemon.GetPokemonByIDRequest
	5, // 5: pokemon.Pokemon.GetPokemonByName:input_type -> pokemon.GetPokemonByNameRequest
	2, // 6: pokemon.Pokemon.ListPokemons:output_type -> pokemon.ListPokemonsResponse
	4, // 7: pokemon.Pokemon.GetPokemonByID:output_type -> pokemon.GetPokemonByIDResponse
	6, // 8: pokemon.Pokemon.GetPokemonByName:output_type -> pokemon.GetPokemonByNameResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_pokemon_pokemon_proto_init() }
func file_proto_pokemon_pokemon_proto_init() {
	if File_proto_pokemon_pokemon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pokemon_pokemon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PokemonInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_pokemon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPokemonsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_pokemon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPokemonsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_pokemon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPokemonByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_pokemon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPokemonByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_pokemon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPokemonByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_pokemon_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPokemonByNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pokemon_pokemon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pokemon_pokemon_proto_goTypes,
		DependencyIndexes: file_proto_pokemon_pokemon_proto_depIdxs,
		MessageInfos:      file_proto_pokemon_pokemon_proto_msgTypes,
	}.Build()
	File_proto_pokemon_pokemon_proto = out.File
	file_proto_pokemon_pokemon_proto_rawDesc = nil
	file_proto_pokemon_pokemon_proto_goTypes = nil
	file_proto_pokemon_pokemon_proto_depIdxs = nil
}
