// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        v3.19.1
// source: proto/ability/ability.proto

package ability

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AbilityInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AbilityId   string   `protobuf:"bytes,1,opt,name=ability_id,json=abilityId,proto3" json:"ability_id,omitempty"`
	AbilityName string   `protobuf:"bytes,2,opt,name=ability_name,json=abilityName,proto3" json:"ability_name,omitempty"`
	Effect      string   `protobuf:"bytes,3,opt,name=effect,proto3" json:"effect,omitempty"`
	PokemonName []string `protobuf:"bytes,4,rep,name=pokemon_name,json=pokemonName,proto3" json:"pokemon_name,omitempty"`
}

func (x *AbilityInfo) Reset() {
	*x = AbilityInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ability_ability_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbilityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbilityInfo) ProtoMessage() {}

func (x *AbilityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ability_ability_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbilityInfo.ProtoReflect.Descriptor instead.
func (*AbilityInfo) Descriptor() ([]byte, []int) {
	return file_proto_ability_ability_proto_rawDescGZIP(), []int{0}
}

func (x *AbilityInfo) GetAbilityId() string {
	if x != nil {
		return x.AbilityId
	}
	return ""
}

func (x *AbilityInfo) GetAbilityName() string {
	if x != nil {
		return x.AbilityName
	}
	return ""
}

func (x *AbilityInfo) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

func (x *AbilityInfo) GetPokemonName() []string {
	if x != nil {
		return x.PokemonName
	}
	return nil
}

type ListAbilitiesRequeset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAbilitiesRequeset) Reset() {
	*x = ListAbilitiesRequeset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ability_ability_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAbilitiesRequeset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAbilitiesRequeset) ProtoMessage() {}

func (x *ListAbilitiesRequeset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ability_ability_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAbilitiesRequeset.ProtoReflect.Descriptor instead.
func (*ListAbilitiesRequeset) Descriptor() ([]byte, []int) {
	return file_proto_ability_ability_proto_rawDescGZIP(), []int{1}
}

type ListAbilitiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AbilityInfos []*AbilityInfo `protobuf:"bytes,1,rep,name=ability_infos,json=abilityInfos,proto3" json:"ability_infos,omitempty"`
}

func (x *ListAbilitiesResponse) Reset() {
	*x = ListAbilitiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ability_ability_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAbilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAbilitiesResponse) ProtoMessage() {}

func (x *ListAbilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ability_ability_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAbilitiesResponse.ProtoReflect.Descriptor instead.
func (*ListAbilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_ability_ability_proto_rawDescGZIP(), []int{2}
}

func (x *ListAbilitiesResponse) GetAbilityInfos() []*AbilityInfo {
	if x != nil {
		return x.AbilityInfos
	}
	return nil
}

type GetAbilityByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AbilityId string `protobuf:"bytes,1,opt,name=ability_id,json=abilityId,proto3" json:"ability_id,omitempty"`
}

func (x *GetAbilityByIDRequest) Reset() {
	*x = GetAbilityByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ability_ability_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAbilityByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbilityByIDRequest) ProtoMessage() {}

func (x *GetAbilityByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ability_ability_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbilityByIDRequest.ProtoReflect.Descriptor instead.
func (*GetAbilityByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_ability_ability_proto_rawDescGZIP(), []int{3}
}

func (x *GetAbilityByIDRequest) GetAbilityId() string {
	if x != nil {
		return x.AbilityId
	}
	return ""
}

type GetAbilityByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AbilityInfo *AbilityInfo `protobuf:"bytes,1,opt,name=ability_info,json=abilityInfo,proto3" json:"ability_info,omitempty"`
}

func (x *GetAbilityByIDResponse) Reset() {
	*x = GetAbilityByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ability_ability_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAbilityByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbilityByIDResponse) ProtoMessage() {}

func (x *GetAbilityByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ability_ability_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbilityByIDResponse.ProtoReflect.Descriptor instead.
func (*GetAbilityByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_ability_ability_proto_rawDescGZIP(), []int{4}
}

func (x *GetAbilityByIDResponse) GetAbilityInfo() *AbilityInfo {
	if x != nil {
		return x.AbilityInfo
	}
	return nil
}

type GetAbilityByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AbilityName string `protobuf:"bytes,1,opt,name=ability_name,json=abilityName,proto3" json:"ability_name,omitempty"`
}

func (x *GetAbilityByNameRequest) Reset() {
	*x = GetAbilityByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ability_ability_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAbilityByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbilityByNameRequest) ProtoMessage() {}

func (x *GetAbilityByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ability_ability_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbilityByNameRequest.ProtoReflect.Descriptor instead.
func (*GetAbilityByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_ability_ability_proto_rawDescGZIP(), []int{5}
}

func (x *GetAbilityByNameRequest) GetAbilityName() string {
	if x != nil {
		return x.AbilityName
	}
	return ""
}

type GetAbilityByNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AbilityInfo *AbilityInfo `protobuf:"bytes,1,opt,name=ability_info,json=abilityInfo,proto3" json:"ability_info,omitempty"`
}

func (x *GetAbilityByNameResponse) Reset() {
	*x = GetAbilityByNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ability_ability_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAbilityByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbilityByNameResponse) ProtoMessage() {}

func (x *GetAbilityByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ability_ability_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbilityByNameResponse.ProtoReflect.Descriptor instead.
func (*GetAbilityByNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_ability_ability_proto_rawDescGZIP(), []int{6}
}

func (x *GetAbilityByNameResponse) GetAbilityInfo() *AbilityInfo {
	if x != nil {
		return x.AbilityInfo
	}
	return nil
}

var File_proto_ability_ability_proto protoreflect.FileDescriptor

var file_proto_ability_ability_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2f,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x0b, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x65, 0x74, 0x22, 0x52, 0x0a, 0x15, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0d, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x2e, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x36,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x42, 0x79, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x37, 0x0a, 0x0c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x2e, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x3c, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x53, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x2e, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0b, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x32, 0xe2, 0x02, 0x0a,
	0x07, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x63, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x65, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x0c, 0x12, 0x0a, 0x2f, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x73, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x42, 0x79, 0x49, 0x44, 0x12,
	0x1e, 0x2e, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x12, 0x18, 0x2f, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x5f, 0x69, 0x64, 0x2f, 0x7b, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x69,
	0x64, 0x7d, 0x12, 0x7d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x2e, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x42, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x42, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x1e, 0x12, 0x1c, 0x2f, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x2f, 0x7b, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x7d, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x62, 0x69, 0x6c, 0x69,
	0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ability_ability_proto_rawDescOnce sync.Once
	file_proto_ability_ability_proto_rawDescData = file_proto_ability_ability_proto_rawDesc
)

func file_proto_ability_ability_proto_rawDescGZIP() []byte {
	file_proto_ability_ability_proto_rawDescOnce.Do(func() {
		file_proto_ability_ability_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ability_ability_proto_rawDescData)
	})
	return file_proto_ability_ability_proto_rawDescData
}

var file_proto_ability_ability_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_ability_ability_proto_goTypes = []interface{}{
	(*AbilityInfo)(nil),              // 0: ability.AbilityInfo
	(*ListAbilitiesRequeset)(nil),    // 1: ability.ListAbilitiesRequeset
	(*ListAbilitiesResponse)(nil),    // 2: ability.ListAbilitiesResponse
	(*GetAbilityByIDRequest)(nil),    // 3: ability.GetAbilityByIDRequest
	(*GetAbilityByIDResponse)(nil),   // 4: ability.GetAbilityByIDResponse
	(*GetAbilityByNameRequest)(nil),  // 5: ability.GetAbilityByNameRequest
	(*GetAbilityByNameResponse)(nil), // 6: ability.GetAbilityByNameResponse
}
var file_proto_ability_ability_proto_depIdxs = []int32{
	0, // 0: ability.ListAbilitiesResponse.ability_infos:type_name -> ability.AbilityInfo
	0, // 1: ability.GetAbilityByIDResponse.ability_info:type_name -> ability.AbilityInfo
	0, // 2: ability.GetAbilityByNameResponse.ability_info:type_name -> ability.AbilityInfo
	1, // 3: ability.Ability.ListAbilities:input_type -> ability.ListAbilitiesRequeset
	3, // 4: ability.Ability.GetAbilityByID:input_type -> ability.GetAbilityByIDRequest
	5, // 5: ability.Ability.GetAbilityByName:input_type -> ability.GetAbilityByNameRequest
	2, // 6: ability.Ability.ListAbilities:output_type -> ability.ListAbilitiesResponse
	4, // 7: ability.Ability.GetAbilityByID:output_type -> ability.GetAbilityByIDResponse
	6, // 8: ability.Ability.GetAbilityByName:output_type -> ability.GetAbilityByNameResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_ability_ability_proto_init() }
func file_proto_ability_ability_proto_init() {
	if File_proto_ability_ability_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ability_ability_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbilityInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ability_ability_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAbilitiesRequeset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ability_ability_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAbilitiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ability_ability_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAbilityByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ability_ability_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAbilityByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ability_ability_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAbilityByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ability_ability_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAbilityByNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ability_ability_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ability_ability_proto_goTypes,
		DependencyIndexes: file_proto_ability_ability_proto_depIdxs,
		MessageInfos:      file_proto_ability_ability_proto_msgTypes,
	}.Build()
	File_proto_ability_ability_proto = out.File
	file_proto_ability_ability_proto_rawDesc = nil
	file_proto_ability_ability_proto_goTypes = nil
	file_proto_ability_ability_proto_depIdxs = nil
}
